CREATE TABLE IF NOT EXISTS BOB_RAW_DATA (
            id UUID DEFAULT UUID_STRING() NOT NULL,
            NAME STRING,
            EMAIL STRING,
            NSS NUMBER,
            TRANSACTION_DATE DATE,
            AMOUNT DECIMAL(6,2),
            CREATED_AT TIMESTAMP_NTZ
)

CREATE OR REPLACE FILE FORMAT SNOWFLAKE_S3_FILE_FORMAT_PARQUET
  TYPE = PARQUET
  COMPRESSION = SNAPPY
  USE_LOGICAL_TYPE = TRUE
  BINARY_AS_TEXT = FALSE
  REPLACE_INVALID_CHARACTERS = TRUE
  COMMENT = 'Customized Parquet file format for data pipeline';

CREATE STORAGE INTEGRATION SNOWFLAKE_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::333989635231:role/snowflake-s3-integration-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://processed-files-bob')

  DESC INTEGRATION SNOWFLAKE_S3_INTEGRATION;

  CREATE STAGE SNOWFLAKE_S3_STAGE
  STORAGE_INTEGRATION = SNOWFLAKE_S3_INTEGRATION
  URL = 's3://processed-files-bob'
  FILE_FORMAT = SNOWFLAKE_S3_FILE_FORMAT_PARQUET;

  GRANT USAGE ON DATABASE BOBTEST TO ROLE BOB_TESTING_INTEGRATION;
  GRANT USAGE ON SCHEMA BOBTEST.BOB TO ROLE BOB_TESTING_INTEGRATION;
  GRANT USAGE ON FILE FORMAT SNOWFLAKE_S3_FILE_FORMAT_PARQUET TO ROLE BOB_TESTING_INTEGRATION;
  GRANT USAGE ON STAGE BOBTEST.BOB.SNOWFLAKE_S3_STAGE TO ROLE BOB_TESTING_INTEGRATION;
  GRANT READ ON STAGE BOBTEST.BOB.SNOWFLAKE_S3_STAGE TO ROLE BOB_TESTING_INTEGRATION;
  GRANT CREATE TABLE ON SCHEMA BOBTEST.BOB TO ROLE BOB_TESTING_INTEGRATION;

  ALTER USER BOBTETS SET MINS_TO_BYPASS_MFA = 60;