CREATE OR REPLACE FILE FORMAT SNOWFLAKE_S3_FILE_FORMAT_PARQUET
  TYPE = PARQUET
  COMPRESSION = SNAPPY
  USE_LOGICAL_TYPE = TRUE
  BINARY_AS_TEXT = FALSE
  REPLACE_INVALID_CHARACTERS = TRUE
  COMMENT = 'Customized Parquet file format for data pipeline';

CREATE STORAGE INTEGRATION SNOWFLAKE_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'snowflake_integration.arn'
  STORAGE_ALLOWED_LOCATIONS = ('s3://processed_files')
  [ STORAGE_BLOCKED_LOCATIONS = () ]

  DESC INTEGRATION SNOWFLAKE_S3_INTEGRATION;

  CREATE STAGE SNOWFLAKE_S3_STAGE
  STORAGE_INTEGRATION = SNOWFLAKE_S3_INTEGRATION
  URL = 's3://processed_files'
  FILE_FORMAT = SNOWFLAKE_S3_FILE_FORMAT_PARQUET;